Header header

ElectromotorsState basic_state

float32 left_electromotor_voltage # bus voltage of the left el.dv.
float32 left_electromotor_current # electric current bus left el.dv.

float32 left_electromotor_temperature # radiator temperature of the driver left el.dv.
float32 left_electromotor_servo_temperature # Kozhukhovo the temperature of the left el.dv.

float32 right_electromotor_voltage # bus voltage right el.dv.
float32 right_electromotor_current # electric current bus right el.dv.

float32 right_electromotor_temperature # radiator temperature of the driver right el.dv.
float32 right_electromotor_servo_temperature # Kozhukhovo right temperature el.dv.
