
/* File generated by gen_cfile.py. Should not be modified. */

#include "actuators.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER64 LEFT_MOTOR_209 = 0x22B;		/* Mapped at index 0x5000, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 actuators_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 actuators_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 actuators_iam_a_slave = 0;

TIMER_HANDLE actuators_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 actuators_obj1000 = 0x0;	/* 0 */
                    subindex actuators_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&actuators_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 actuators_obj1001 = 0x0;	/* 0 */
                    subindex actuators_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 actuators_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t actuators_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&actuators_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 actuators_obj1005 = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex actuators_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 actuators_obj1006 = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex actuators_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 actuators_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 actuators_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 actuators_obj1014 = 0x80;	/* 128 */
                    subindex actuators_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 actuators_highestSubIndex_obj1016 = 0;
                    UNS32 actuators_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 actuators_obj1017 = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex actuators_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 actuators_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 actuators_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 actuators_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 actuators_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 actuators_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex actuators_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&actuators_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&actuators_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&actuators_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&actuators_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 actuators_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex actuators_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 actuators_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1281_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex actuators_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 actuators_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 actuators_obj1282_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex actuators_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 actuators_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 actuators_obj1283_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex actuators_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 actuators_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 actuators_obj1284_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex actuators_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 actuators_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 actuators_obj1285_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex actuators_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1285 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1285_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1285_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1285_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 actuators_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 actuators_obj1286_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    subindex actuators_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1286 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1286_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1286_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1286_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 actuators_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 actuators_obj1287_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex actuators_Index1287[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1287 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1287_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1287_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1287_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1288 :   Client SDO 9 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1288 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1288_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 actuators_obj1288_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 actuators_obj1288_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex actuators_Index1288[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1288 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1288_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1288_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1288_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1289 :   Client SDO 10 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1289 = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj1289_COB_ID_Client_to_Server_Transmit_SDO = 0x609;	/* 1545 */
                    UNS32 actuators_obj1289_COB_ID_Server_to_Client_Receive_SDO = 0x589;	/* 1417 */
                    UNS8 actuators_obj1289_Node_ID_of_the_SDO_Server = 0x9;	/* 9 */
                    subindex actuators_Index1289[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1289 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1289_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1289_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1289_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128A :   Client SDO 11 Parameter. */
                    UNS8 actuators_highestSubIndex_obj128A = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj128A_COB_ID_Client_to_Server_Transmit_SDO = 0x60A;	/* 1546 */
                    UNS32 actuators_obj128A_COB_ID_Server_to_Client_Receive_SDO = 0x60A;	/* 1546 */
                    UNS8 actuators_obj128A_Node_ID_of_the_SDO_Server = 0xA;	/* 10 */
                    subindex actuators_Index128A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj128A },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj128A_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj128A_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj128A_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128B :   Client SDO 12 Parameter. */
                    UNS8 actuators_highestSubIndex_obj128B = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj128B_COB_ID_Client_to_Server_Transmit_SDO = 0x60B;	/* 1547 */
                    UNS32 actuators_obj128B_COB_ID_Server_to_Client_Receive_SDO = 0x58B;	/* 1419 */
                    UNS8 actuators_obj128B_Node_ID_of_the_SDO_Server = 0xB;	/* 11 */
                    subindex actuators_Index128B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj128B },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj128B_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj128B_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj128B_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128C :   Client SDO 13 Parameter. */
                    UNS8 actuators_highestSubIndex_obj128C = 3; /* number of subindex - 1*/
                    UNS32 actuators_obj128C_COB_ID_Client_to_Server_Transmit_SDO = 0x60C;	/* 1548 */
                    UNS32 actuators_obj128C_COB_ID_Server_to_Client_Receive_SDO = 0x58C;	/* 1420 */
                    UNS8 actuators_obj128C_Node_ID_of_the_SDO_Server = 0xC;	/* 12 */
                    subindex actuators_Index128C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj128C },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj128C_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj128C_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj128C_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1800_COB_ID_used_by_PDO = 0x20B;	/* 523 */
                    UNS8 actuators_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 actuators_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 actuators_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 actuators_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1803_SYNC_start_value }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1804 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1804_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1804_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1804_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1804_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1804_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1804[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1804 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1804_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1804_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1804_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1804_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1804_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1804_SYNC_start_value }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1805 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1805_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1805_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1805_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1805_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1805_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1805[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1805 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1805_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1805_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1805_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1805_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1805_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1805_SYNC_start_value }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1806 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1806_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1806_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1806_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1806_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1806_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1806_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1806[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1806 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1806_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1806_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1806_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1806_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1806_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1806_SYNC_start_value }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1807 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1807_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1807_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1807_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1807_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1807_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1807_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1807[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1807 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1807_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1807_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1807_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1807_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1807_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1807_SYNC_start_value }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1808 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1808_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1808_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1808_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1808_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1808_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1808_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1808[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1808 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1808_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1808_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1808_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1808_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1808_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1808_SYNC_start_value }
                     };

/* index 0x1809 :   Transmit PDO 10 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1809 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1809_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1809_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1809_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1809_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1809_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1809_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1809_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1809[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1809 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1809_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1809_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1809_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1809_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1809_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1809_SYNC_start_value }
                     };

/* index 0x180A :   Transmit PDO 11 Parameter. */
                    UNS8 actuators_highestSubIndex_obj180A = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj180A_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj180A_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj180A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj180A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj180A_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj180A_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index180A_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index180A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj180A },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj180A_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180A_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180A_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180A_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180A_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180A_SYNC_start_value }
                     };

/* index 0x180B :   Transmit PDO 12 Parameter. */
                    UNS8 actuators_highestSubIndex_obj180B = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj180B_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj180B_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj180B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj180B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj180B_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj180B_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index180B_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index180B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj180B },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj180B_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180B_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180B_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180B_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180B_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180B_SYNC_start_value }
                     };

/* index 0x180C :   Transmit PDO 13 Parameter. */
                    UNS8 actuators_highestSubIndex_obj180C = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj180C_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj180C_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj180C_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj180C_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj180C_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj180C_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index180C_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index180C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj180C },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj180C_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180C_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180C_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180C_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180C_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180C_SYNC_start_value }
                     };

/* index 0x180D :   Transmit PDO 14 Parameter. */
                    UNS8 actuators_highestSubIndex_obj180D = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj180D_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj180D_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj180D_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj180D_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj180D_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj180D_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index180D_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index180D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj180D },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj180D_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180D_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180D_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180D_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180D_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180D_SYNC_start_value }
                     };

/* index 0x180E :   Transmit PDO 15 Parameter. */
                    UNS8 actuators_highestSubIndex_obj180E = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj180E_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj180E_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj180E_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj180E_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj180E_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj180E_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index180E_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index180E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj180E },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj180E_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180E_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180E_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180E_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180E_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180E_SYNC_start_value }
                     };

/* index 0x180F :   Transmit PDO 16 Parameter. */
                    UNS8 actuators_highestSubIndex_obj180F = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj180F_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj180F_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj180F_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj180F_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj180F_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj180F_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index180F_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index180F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj180F },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj180F_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180F_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180F_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180F_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj180F_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj180F_SYNC_start_value }
                     };

/* index 0x1810 :   Transmit PDO 17 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1810 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1810_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1810_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1810_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1810_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1810_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1810_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1810_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1810[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1810 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1810_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1810_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1810_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1810_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1810_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1810_SYNC_start_value }
                     };

/* index 0x1811 :   Transmit PDO 18 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1811 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1811_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1811_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1811_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1811_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1811_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1811_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1811_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1811[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1811 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1811_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1811_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1811_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1811_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1811_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1811_SYNC_start_value }
                     };

/* index 0x1812 :   Transmit PDO 19 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1812 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1812_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1812_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1812_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1812_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1812_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1812_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1812_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1812[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1812 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1812_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1812_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1812_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1812_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1812_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1812_SYNC_start_value }
                     };

/* index 0x1813 :   Transmit PDO 20 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1813 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1813_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1813_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1813_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1813_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1813_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1813_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1813_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1813[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1813 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1813_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1813_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1813_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1813_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1813_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1813_SYNC_start_value }
                     };

/* index 0x1814 :   Transmit PDO 21 Parameter. */
                    UNS8 actuators_highestSubIndex_obj1814 = 6; /* number of subindex - 1*/
                    UNS32 actuators_obj1814_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 actuators_obj1814_Transmission_Type = 0x0;	/* 0 */
                    UNS16 actuators_obj1814_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 actuators_obj1814_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 actuators_obj1814_Event_Timer = 0x0;	/* 0 */
                    UNS8 actuators_obj1814_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t actuators_Index1814_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex actuators_Index1814[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1814 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1814_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1814_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1814_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1814_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&actuators_obj1814_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_obj1814_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 actuators_obj1A00[] = 
                    {
                      0x50000040	/* 1342177344 */
                    };
                    subindex actuators_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&actuators_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A01 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A01[] = 
                    {
                    };
                    subindex actuators_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A01 }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A02 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A02[] = 
                    {
                    };
                    subindex actuators_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A02 }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A03 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A03[] = 
                    {
                    };
                    subindex actuators_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A03 }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A04 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A04[] = 
                    {
                    };
                    subindex actuators_Index1A04[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A04 }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A05 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A05[] = 
                    {
                    };
                    subindex actuators_Index1A05[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A05 }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A06 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A06[] = 
                    {
                    };
                    subindex actuators_Index1A06[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A06 }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A07 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A07[] = 
                    {
                    };
                    subindex actuators_Index1A07[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A07 }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A08 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A08[] = 
                    {
                    };
                    subindex actuators_Index1A08[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A08 }
                     };

/* index 0x1A09 :   Transmit PDO 10 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A09 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A09[] = 
                    {
                    };
                    subindex actuators_Index1A09[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A09 }
                     };

/* index 0x1A0A :   Transmit PDO 11 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A0A = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A0A[] = 
                    {
                    };
                    subindex actuators_Index1A0A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A0A }
                     };

/* index 0x1A0B :   Transmit PDO 12 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A0B = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A0B[] = 
                    {
                    };
                    subindex actuators_Index1A0B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A0B }
                     };

/* index 0x1A0C :   Transmit PDO 13 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A0C = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A0C[] = 
                    {
                    };
                    subindex actuators_Index1A0C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A0C }
                     };

/* index 0x1A0D :   Transmit PDO 14 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A0D = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A0D[] = 
                    {
                    };
                    subindex actuators_Index1A0D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A0D }
                     };

/* index 0x1A0E :   Transmit PDO 15 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A0E = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A0E[] = 
                    {
                    };
                    subindex actuators_Index1A0E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A0E }
                     };

/* index 0x1A0F :   Transmit PDO 16 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A0F = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A0F[] = 
                    {
                    };
                    subindex actuators_Index1A0F[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A0F }
                     };

/* index 0x1A10 :   Transmit PDO 17 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A10 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A10[] = 
                    {
                    };
                    subindex actuators_Index1A10[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A10 }
                     };

/* index 0x1A11 :   Transmit PDO 18 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A11 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A11[] = 
                    {
                    };
                    subindex actuators_Index1A11[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A11 }
                     };

/* index 0x1A12 :   Transmit PDO 19 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A12 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A12[] = 
                    {
                    };
                    subindex actuators_Index1A12[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A12 }
                     };

/* index 0x1A13 :   Transmit PDO 20 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A13 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A13[] = 
                    {
                    };
                    subindex actuators_Index1A13[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A13 }
                     };

/* index 0x1A14 :   Transmit PDO 21 Mapping. */
                    UNS8 actuators_highestSubIndex_obj1A14 = 0; /* number of subindex - 1*/
                    UNS32 actuators_obj1A14[] = 
                    {
                    };
                    subindex actuators_Index1A14[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&actuators_highestSubIndex_obj1A14 }
                     };

/* index 0x5000 :   Mapped variable LEFT_MOTOR_209 */
                    ODCallback_t LEFT_MOTOR_209_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex actuators_Index5000[] = 
                     {
                       { RW, int64, sizeof (INTEGER64), (void*)&LEFT_MOTOR_209 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable actuators_objdict[] = 
{
  { (subindex*)actuators_Index1000,sizeof(actuators_Index1000)/sizeof(actuators_Index1000[0]), 0x1000},
  { (subindex*)actuators_Index1001,sizeof(actuators_Index1001)/sizeof(actuators_Index1001[0]), 0x1001},
  { (subindex*)actuators_Index1005,sizeof(actuators_Index1005)/sizeof(actuators_Index1005[0]), 0x1005},
  { (subindex*)actuators_Index1006,sizeof(actuators_Index1006)/sizeof(actuators_Index1006[0]), 0x1006},
  { (subindex*)actuators_Index1014,sizeof(actuators_Index1014)/sizeof(actuators_Index1014[0]), 0x1014},
  { (subindex*)actuators_Index1017,sizeof(actuators_Index1017)/sizeof(actuators_Index1017[0]), 0x1017},
  { (subindex*)actuators_Index1018,sizeof(actuators_Index1018)/sizeof(actuators_Index1018[0]), 0x1018},
  { (subindex*)actuators_Index1280,sizeof(actuators_Index1280)/sizeof(actuators_Index1280[0]), 0x1280},
  { (subindex*)actuators_Index1281,sizeof(actuators_Index1281)/sizeof(actuators_Index1281[0]), 0x1281},
  { (subindex*)actuators_Index1282,sizeof(actuators_Index1282)/sizeof(actuators_Index1282[0]), 0x1282},
  { (subindex*)actuators_Index1283,sizeof(actuators_Index1283)/sizeof(actuators_Index1283[0]), 0x1283},
  { (subindex*)actuators_Index1284,sizeof(actuators_Index1284)/sizeof(actuators_Index1284[0]), 0x1284},
  { (subindex*)actuators_Index1285,sizeof(actuators_Index1285)/sizeof(actuators_Index1285[0]), 0x1285},
  { (subindex*)actuators_Index1286,sizeof(actuators_Index1286)/sizeof(actuators_Index1286[0]), 0x1286},
  { (subindex*)actuators_Index1287,sizeof(actuators_Index1287)/sizeof(actuators_Index1287[0]), 0x1287},
  { (subindex*)actuators_Index1288,sizeof(actuators_Index1288)/sizeof(actuators_Index1288[0]), 0x1288},
  { (subindex*)actuators_Index1289,sizeof(actuators_Index1289)/sizeof(actuators_Index1289[0]), 0x1289},
  { (subindex*)actuators_Index128A,sizeof(actuators_Index128A)/sizeof(actuators_Index128A[0]), 0x128A},
  { (subindex*)actuators_Index128B,sizeof(actuators_Index128B)/sizeof(actuators_Index128B[0]), 0x128B},
  { (subindex*)actuators_Index128C,sizeof(actuators_Index128C)/sizeof(actuators_Index128C[0]), 0x128C},
  { (subindex*)actuators_Index1800,sizeof(actuators_Index1800)/sizeof(actuators_Index1800[0]), 0x1800},
  { (subindex*)actuators_Index1801,sizeof(actuators_Index1801)/sizeof(actuators_Index1801[0]), 0x1801},
  { (subindex*)actuators_Index1802,sizeof(actuators_Index1802)/sizeof(actuators_Index1802[0]), 0x1802},
  { (subindex*)actuators_Index1803,sizeof(actuators_Index1803)/sizeof(actuators_Index1803[0]), 0x1803},
  { (subindex*)actuators_Index1804,sizeof(actuators_Index1804)/sizeof(actuators_Index1804[0]), 0x1804},
  { (subindex*)actuators_Index1805,sizeof(actuators_Index1805)/sizeof(actuators_Index1805[0]), 0x1805},
  { (subindex*)actuators_Index1806,sizeof(actuators_Index1806)/sizeof(actuators_Index1806[0]), 0x1806},
  { (subindex*)actuators_Index1807,sizeof(actuators_Index1807)/sizeof(actuators_Index1807[0]), 0x1807},
  { (subindex*)actuators_Index1808,sizeof(actuators_Index1808)/sizeof(actuators_Index1808[0]), 0x1808},
  { (subindex*)actuators_Index1809,sizeof(actuators_Index1809)/sizeof(actuators_Index1809[0]), 0x1809},
  { (subindex*)actuators_Index180A,sizeof(actuators_Index180A)/sizeof(actuators_Index180A[0]), 0x180A},
  { (subindex*)actuators_Index180B,sizeof(actuators_Index180B)/sizeof(actuators_Index180B[0]), 0x180B},
  { (subindex*)actuators_Index180C,sizeof(actuators_Index180C)/sizeof(actuators_Index180C[0]), 0x180C},
  { (subindex*)actuators_Index180D,sizeof(actuators_Index180D)/sizeof(actuators_Index180D[0]), 0x180D},
  { (subindex*)actuators_Index180E,sizeof(actuators_Index180E)/sizeof(actuators_Index180E[0]), 0x180E},
  { (subindex*)actuators_Index180F,sizeof(actuators_Index180F)/sizeof(actuators_Index180F[0]), 0x180F},
  { (subindex*)actuators_Index1810,sizeof(actuators_Index1810)/sizeof(actuators_Index1810[0]), 0x1810},
  { (subindex*)actuators_Index1811,sizeof(actuators_Index1811)/sizeof(actuators_Index1811[0]), 0x1811},
  { (subindex*)actuators_Index1812,sizeof(actuators_Index1812)/sizeof(actuators_Index1812[0]), 0x1812},
  { (subindex*)actuators_Index1813,sizeof(actuators_Index1813)/sizeof(actuators_Index1813[0]), 0x1813},
  { (subindex*)actuators_Index1814,sizeof(actuators_Index1814)/sizeof(actuators_Index1814[0]), 0x1814},
  { (subindex*)actuators_Index1A00,sizeof(actuators_Index1A00)/sizeof(actuators_Index1A00[0]), 0x1A00},
  { (subindex*)actuators_Index1A01,sizeof(actuators_Index1A01)/sizeof(actuators_Index1A01[0]), 0x1A01},
  { (subindex*)actuators_Index1A02,sizeof(actuators_Index1A02)/sizeof(actuators_Index1A02[0]), 0x1A02},
  { (subindex*)actuators_Index1A03,sizeof(actuators_Index1A03)/sizeof(actuators_Index1A03[0]), 0x1A03},
  { (subindex*)actuators_Index1A04,sizeof(actuators_Index1A04)/sizeof(actuators_Index1A04[0]), 0x1A04},
  { (subindex*)actuators_Index1A05,sizeof(actuators_Index1A05)/sizeof(actuators_Index1A05[0]), 0x1A05},
  { (subindex*)actuators_Index1A06,sizeof(actuators_Index1A06)/sizeof(actuators_Index1A06[0]), 0x1A06},
  { (subindex*)actuators_Index1A07,sizeof(actuators_Index1A07)/sizeof(actuators_Index1A07[0]), 0x1A07},
  { (subindex*)actuators_Index1A08,sizeof(actuators_Index1A08)/sizeof(actuators_Index1A08[0]), 0x1A08},
  { (subindex*)actuators_Index1A09,sizeof(actuators_Index1A09)/sizeof(actuators_Index1A09[0]), 0x1A09},
  { (subindex*)actuators_Index1A0A,sizeof(actuators_Index1A0A)/sizeof(actuators_Index1A0A[0]), 0x1A0A},
  { (subindex*)actuators_Index1A0B,sizeof(actuators_Index1A0B)/sizeof(actuators_Index1A0B[0]), 0x1A0B},
  { (subindex*)actuators_Index1A0C,sizeof(actuators_Index1A0C)/sizeof(actuators_Index1A0C[0]), 0x1A0C},
  { (subindex*)actuators_Index1A0D,sizeof(actuators_Index1A0D)/sizeof(actuators_Index1A0D[0]), 0x1A0D},
  { (subindex*)actuators_Index1A0E,sizeof(actuators_Index1A0E)/sizeof(actuators_Index1A0E[0]), 0x1A0E},
  { (subindex*)actuators_Index1A0F,sizeof(actuators_Index1A0F)/sizeof(actuators_Index1A0F[0]), 0x1A0F},
  { (subindex*)actuators_Index1A10,sizeof(actuators_Index1A10)/sizeof(actuators_Index1A10[0]), 0x1A10},
  { (subindex*)actuators_Index1A11,sizeof(actuators_Index1A11)/sizeof(actuators_Index1A11[0]), 0x1A11},
  { (subindex*)actuators_Index1A12,sizeof(actuators_Index1A12)/sizeof(actuators_Index1A12[0]), 0x1A12},
  { (subindex*)actuators_Index1A13,sizeof(actuators_Index1A13)/sizeof(actuators_Index1A13[0]), 0x1A13},
  { (subindex*)actuators_Index1A14,sizeof(actuators_Index1A14)/sizeof(actuators_Index1A14[0]), 0x1A14},
  { (subindex*)actuators_Index5000,sizeof(actuators_Index5000)/sizeof(actuators_Index5000[0]), 0x5000},
};

const indextable * actuators_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = actuators_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = actuators_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1017: i = 5;*callbacks = actuators_Index1017_callbacks; break;
		case 0x1018: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1281: i = 8;break;
		case 0x1282: i = 9;break;
		case 0x1283: i = 10;break;
		case 0x1284: i = 11;break;
		case 0x1285: i = 12;break;
		case 0x1286: i = 13;break;
		case 0x1287: i = 14;break;
		case 0x1288: i = 15;break;
		case 0x1289: i = 16;break;
		case 0x128A: i = 17;break;
		case 0x128B: i = 18;break;
		case 0x128C: i = 19;break;
		case 0x1800: i = 20;*callbacks = actuators_Index1800_callbacks; break;
		case 0x1801: i = 21;*callbacks = actuators_Index1801_callbacks; break;
		case 0x1802: i = 22;*callbacks = actuators_Index1802_callbacks; break;
		case 0x1803: i = 23;*callbacks = actuators_Index1803_callbacks; break;
		case 0x1804: i = 24;*callbacks = actuators_Index1804_callbacks; break;
		case 0x1805: i = 25;*callbacks = actuators_Index1805_callbacks; break;
		case 0x1806: i = 26;*callbacks = actuators_Index1806_callbacks; break;
		case 0x1807: i = 27;*callbacks = actuators_Index1807_callbacks; break;
		case 0x1808: i = 28;*callbacks = actuators_Index1808_callbacks; break;
		case 0x1809: i = 29;*callbacks = actuators_Index1809_callbacks; break;
		case 0x180A: i = 30;*callbacks = actuators_Index180A_callbacks; break;
		case 0x180B: i = 31;*callbacks = actuators_Index180B_callbacks; break;
		case 0x180C: i = 32;*callbacks = actuators_Index180C_callbacks; break;
		case 0x180D: i = 33;*callbacks = actuators_Index180D_callbacks; break;
		case 0x180E: i = 34;*callbacks = actuators_Index180E_callbacks; break;
		case 0x180F: i = 35;*callbacks = actuators_Index180F_callbacks; break;
		case 0x1810: i = 36;*callbacks = actuators_Index1810_callbacks; break;
		case 0x1811: i = 37;*callbacks = actuators_Index1811_callbacks; break;
		case 0x1812: i = 38;*callbacks = actuators_Index1812_callbacks; break;
		case 0x1813: i = 39;*callbacks = actuators_Index1813_callbacks; break;
		case 0x1814: i = 40;*callbacks = actuators_Index1814_callbacks; break;
		case 0x1A00: i = 41;break;
		case 0x1A01: i = 42;break;
		case 0x1A02: i = 43;break;
		case 0x1A03: i = 44;break;
		case 0x1A04: i = 45;break;
		case 0x1A05: i = 46;break;
		case 0x1A06: i = 47;break;
		case 0x1A07: i = 48;break;
		case 0x1A08: i = 49;break;
		case 0x1A09: i = 50;break;
		case 0x1A0A: i = 51;break;
		case 0x1A0B: i = 52;break;
		case 0x1A0C: i = 53;break;
		case 0x1A0D: i = 54;break;
		case 0x1A0E: i = 55;break;
		case 0x1A0F: i = 56;break;
		case 0x1A10: i = 57;break;
		case 0x1A11: i = 58;break;
		case 0x1A12: i = 59;break;
		case 0x1A13: i = 60;break;
		case 0x1A14: i = 61;break;
		case 0x5000: i = 62;*callbacks = LEFT_MOTOR_209_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &actuators_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status actuators_PDO_status[21] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index actuators_firstIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  20, /* PDO_TRS */
  41 /* PDO_TRS_MAP */
};

const quick_index actuators_lastIndex = {
  0, /* SDO_SVR */
  19, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  40, /* PDO_TRS */
  61 /* PDO_TRS_MAP */
};

const UNS16 actuators_ObjdictSize = sizeof(actuators_objdict)/sizeof(actuators_objdict[0]); 

CO_Data actuators_Data = CANOPEN_NODE_DATA_INITIALIZER(actuators);

