"""autogenerated by genpy from actuators/BallonetState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class BallonetState(genpy.Message):
  _md5sum = "015af87c2b26b12c8dfae8fdc0880ebe"
  _type = "actuators/BallonetState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

# 
float64 pressureDiff1
float64 pressureDiff2

bool fan1				# 
bool fan2				# 
	
bool valve				# 
bool valve_helium		# 
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','pressureDiff1','pressureDiff2','fan1','fan2','valve','valve_helium']
  _slot_types = ['std_msgs/Header','float64','float64','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pressureDiff1,pressureDiff2,fan1,fan2,valve,valve_helium

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BallonetState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pressureDiff1 is None:
        self.pressureDiff1 = 0.
      if self.pressureDiff2 is None:
        self.pressureDiff2 = 0.
      if self.fan1 is None:
        self.fan1 = False
      if self.fan2 is None:
        self.fan2 = False
      if self.valve is None:
        self.valve = False
      if self.valve_helium is None:
        self.valve_helium = False
    else:
      self.header = std_msgs.msg.Header()
      self.pressureDiff1 = 0.
      self.pressureDiff2 = 0.
      self.fan1 = False
      self.fan2 = False
      self.valve = False
      self.valve_helium = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2d4B.pack(_x.pressureDiff1, _x.pressureDiff2, _x.fan1, _x.fan2, _x.valve, _x.valve_helium))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.pressureDiff1, _x.pressureDiff2, _x.fan1, _x.fan2, _x.valve, _x.valve_helium,) = _struct_2d4B.unpack(str[start:end])
      self.fan1 = bool(self.fan1)
      self.fan2 = bool(self.fan2)
      self.valve = bool(self.valve)
      self.valve_helium = bool(self.valve_helium)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2d4B.pack(_x.pressureDiff1, _x.pressureDiff2, _x.fan1, _x.fan2, _x.valve, _x.valve_helium))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.pressureDiff1, _x.pressureDiff2, _x.fan1, _x.fan2, _x.valve, _x.valve_helium,) = _struct_2d4B.unpack(str[start:end])
      self.fan1 = bool(self.fan1)
      self.fan2 = bool(self.fan2)
      self.valve = bool(self.valve)
      self.valve_helium = bool(self.valve_helium)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d4B = struct.Struct("<2d4B")
_struct_3I = struct.Struct("<3I")
