"""autogenerated by genpy from actuators/ElectromotorsStateExt.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actuators.msg
import std_msgs.msg

class ElectromotorsStateExt(genpy.Message):
  _md5sum = "52e7da340c19977961fab57edfb9e77a"
  _type = "actuators/ElectromotorsStateExt"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

ElectromotorsState basic_state

float32 left_electromotor_voltage # bus voltage of the left el.dv.
float32 left_electromotor_current # electric current bus left el.dv.

float32 left_electromotor_temperature # radiator temperature of the driver left el.dv.
float32 left_electromotor_servo_temperature # Kozhukhovo the temperature of the left el.dv.

float32 right_electromotor_voltage # bus voltage right el.dv.
float32 right_electromotor_current # electric current bus right el.dv.

float32 right_electromotor_temperature # radiator temperature of the driver right el.dv.
float32 right_electromotor_servo_temperature # Kozhukhovo right temperature el.dv.

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actuators/ElectromotorsState
Header header

ElectromotorState left_em
ElectromotorState right_em
ElectromotorServoState left_em_servo
ElectromotorServoState right_em_servo
================================================================================
MSG: actuators/ElectromotorState
Header header

# 
float32 rate
================================================================================
MSG: actuators/ElectromotorServoState
Header header

# 
float32 anglex
float32 angley
#  
bool fix
"""
  __slots__ = ['header','basic_state','left_electromotor_voltage','left_electromotor_current','left_electromotor_temperature','left_electromotor_servo_temperature','right_electromotor_voltage','right_electromotor_current','right_electromotor_temperature','right_electromotor_servo_temperature']
  _slot_types = ['std_msgs/Header','actuators/ElectromotorsState','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,basic_state,left_electromotor_voltage,left_electromotor_current,left_electromotor_temperature,left_electromotor_servo_temperature,right_electromotor_voltage,right_electromotor_current,right_electromotor_temperature,right_electromotor_servo_temperature

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ElectromotorsStateExt, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.basic_state is None:
        self.basic_state = actuators.msg.ElectromotorsState()
      if self.left_electromotor_voltage is None:
        self.left_electromotor_voltage = 0.
      if self.left_electromotor_current is None:
        self.left_electromotor_current = 0.
      if self.left_electromotor_temperature is None:
        self.left_electromotor_temperature = 0.
      if self.left_electromotor_servo_temperature is None:
        self.left_electromotor_servo_temperature = 0.
      if self.right_electromotor_voltage is None:
        self.right_electromotor_voltage = 0.
      if self.right_electromotor_current is None:
        self.right_electromotor_current = 0.
      if self.right_electromotor_temperature is None:
        self.right_electromotor_temperature = 0.
      if self.right_electromotor_servo_temperature is None:
        self.right_electromotor_servo_temperature = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.basic_state = actuators.msg.ElectromotorsState()
      self.left_electromotor_voltage = 0.
      self.left_electromotor_current = 0.
      self.left_electromotor_temperature = 0.
      self.left_electromotor_servo_temperature = 0.
      self.right_electromotor_voltage = 0.
      self.right_electromotor_current = 0.
      self.right_electromotor_temperature = 0.
      self.right_electromotor_servo_temperature = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.basic_state.header.seq, _x.basic_state.header.stamp.secs, _x.basic_state.header.stamp.nsecs))
      _x = self.basic_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.basic_state.left_em.header.seq, _x.basic_state.left_em.header.stamp.secs, _x.basic_state.left_em.header.stamp.nsecs))
      _x = self.basic_state.left_em.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f3I.pack(_x.basic_state.left_em.rate, _x.basic_state.right_em.header.seq, _x.basic_state.right_em.header.stamp.secs, _x.basic_state.right_em.header.stamp.nsecs))
      _x = self.basic_state.right_em.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f3I.pack(_x.basic_state.right_em.rate, _x.basic_state.left_em_servo.header.seq, _x.basic_state.left_em_servo.header.stamp.secs, _x.basic_state.left_em_servo.header.stamp.nsecs))
      _x = self.basic_state.left_em_servo.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2fB3I.pack(_x.basic_state.left_em_servo.anglex, _x.basic_state.left_em_servo.angley, _x.basic_state.left_em_servo.fix, _x.basic_state.right_em_servo.header.seq, _x.basic_state.right_em_servo.header.stamp.secs, _x.basic_state.right_em_servo.header.stamp.nsecs))
      _x = self.basic_state.right_em_servo.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2fB8f.pack(_x.basic_state.right_em_servo.anglex, _x.basic_state.right_em_servo.angley, _x.basic_state.right_em_servo.fix, _x.left_electromotor_voltage, _x.left_electromotor_current, _x.left_electromotor_temperature, _x.left_electromotor_servo_temperature, _x.right_electromotor_voltage, _x.right_electromotor_current, _x.right_electromotor_temperature, _x.right_electromotor_servo_temperature))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.basic_state is None:
        self.basic_state = actuators.msg.ElectromotorsState()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.basic_state.header.seq, _x.basic_state.header.stamp.secs, _x.basic_state.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.basic_state.left_em.header.seq, _x.basic_state.left_em.header.stamp.secs, _x.basic_state.left_em.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.left_em.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.left_em.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.basic_state.left_em.rate, _x.basic_state.right_em.header.seq, _x.basic_state.right_em.header.stamp.secs, _x.basic_state.right_em.header.stamp.nsecs,) = _struct_f3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.right_em.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.right_em.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.basic_state.right_em.rate, _x.basic_state.left_em_servo.header.seq, _x.basic_state.left_em_servo.header.stamp.secs, _x.basic_state.left_em_servo.header.stamp.nsecs,) = _struct_f3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.left_em_servo.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.left_em_servo.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 21
      (_x.basic_state.left_em_servo.anglex, _x.basic_state.left_em_servo.angley, _x.basic_state.left_em_servo.fix, _x.basic_state.right_em_servo.header.seq, _x.basic_state.right_em_servo.header.stamp.secs, _x.basic_state.right_em_servo.header.stamp.nsecs,) = _struct_2fB3I.unpack(str[start:end])
      self.basic_state.left_em_servo.fix = bool(self.basic_state.left_em_servo.fix)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.right_em_servo.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.right_em_servo.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.basic_state.right_em_servo.anglex, _x.basic_state.right_em_servo.angley, _x.basic_state.right_em_servo.fix, _x.left_electromotor_voltage, _x.left_electromotor_current, _x.left_electromotor_temperature, _x.left_electromotor_servo_temperature, _x.right_electromotor_voltage, _x.right_electromotor_current, _x.right_electromotor_temperature, _x.right_electromotor_servo_temperature,) = _struct_2fB8f.unpack(str[start:end])
      self.basic_state.right_em_servo.fix = bool(self.basic_state.right_em_servo.fix)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.basic_state.header.seq, _x.basic_state.header.stamp.secs, _x.basic_state.header.stamp.nsecs))
      _x = self.basic_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.basic_state.left_em.header.seq, _x.basic_state.left_em.header.stamp.secs, _x.basic_state.left_em.header.stamp.nsecs))
      _x = self.basic_state.left_em.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f3I.pack(_x.basic_state.left_em.rate, _x.basic_state.right_em.header.seq, _x.basic_state.right_em.header.stamp.secs, _x.basic_state.right_em.header.stamp.nsecs))
      _x = self.basic_state.right_em.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f3I.pack(_x.basic_state.right_em.rate, _x.basic_state.left_em_servo.header.seq, _x.basic_state.left_em_servo.header.stamp.secs, _x.basic_state.left_em_servo.header.stamp.nsecs))
      _x = self.basic_state.left_em_servo.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2fB3I.pack(_x.basic_state.left_em_servo.anglex, _x.basic_state.left_em_servo.angley, _x.basic_state.left_em_servo.fix, _x.basic_state.right_em_servo.header.seq, _x.basic_state.right_em_servo.header.stamp.secs, _x.basic_state.right_em_servo.header.stamp.nsecs))
      _x = self.basic_state.right_em_servo.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2fB8f.pack(_x.basic_state.right_em_servo.anglex, _x.basic_state.right_em_servo.angley, _x.basic_state.right_em_servo.fix, _x.left_electromotor_voltage, _x.left_electromotor_current, _x.left_electromotor_temperature, _x.left_electromotor_servo_temperature, _x.right_electromotor_voltage, _x.right_electromotor_current, _x.right_electromotor_temperature, _x.right_electromotor_servo_temperature))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.basic_state is None:
        self.basic_state = actuators.msg.ElectromotorsState()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.basic_state.header.seq, _x.basic_state.header.stamp.secs, _x.basic_state.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.basic_state.left_em.header.seq, _x.basic_state.left_em.header.stamp.secs, _x.basic_state.left_em.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.left_em.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.left_em.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.basic_state.left_em.rate, _x.basic_state.right_em.header.seq, _x.basic_state.right_em.header.stamp.secs, _x.basic_state.right_em.header.stamp.nsecs,) = _struct_f3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.right_em.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.right_em.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.basic_state.right_em.rate, _x.basic_state.left_em_servo.header.seq, _x.basic_state.left_em_servo.header.stamp.secs, _x.basic_state.left_em_servo.header.stamp.nsecs,) = _struct_f3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.left_em_servo.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.left_em_servo.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 21
      (_x.basic_state.left_em_servo.anglex, _x.basic_state.left_em_servo.angley, _x.basic_state.left_em_servo.fix, _x.basic_state.right_em_servo.header.seq, _x.basic_state.right_em_servo.header.stamp.secs, _x.basic_state.right_em_servo.header.stamp.nsecs,) = _struct_2fB3I.unpack(str[start:end])
      self.basic_state.left_em_servo.fix = bool(self.basic_state.left_em_servo.fix)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.basic_state.right_em_servo.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.basic_state.right_em_servo.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.basic_state.right_em_servo.anglex, _x.basic_state.right_em_servo.angley, _x.basic_state.right_em_servo.fix, _x.left_electromotor_voltage, _x.left_electromotor_current, _x.left_electromotor_temperature, _x.left_electromotor_servo_temperature, _x.right_electromotor_voltage, _x.right_electromotor_current, _x.right_electromotor_temperature, _x.right_electromotor_servo_temperature,) = _struct_2fB8f.unpack(str[start:end])
      self.basic_state.right_em_servo.fix = bool(self.basic_state.right_em_servo.fix)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_f3I = struct.Struct("<f3I")
_struct_3I = struct.Struct("<3I")
_struct_2fB3I = struct.Struct("<2fB3I")
_struct_2fB8f = struct.Struct("<2fB8f")
