"""autogenerated by genpy from actuators/EngineStateExt.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EngineStateExt(genpy.Message):
  _md5sum = "d4abaec23c08ac439ded0946d56b6980"
  _type = "actuators/EngineStateExt"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

bool ignition_1
bool ignition_2
bool servo
bool magnetic_valve # reserved
bool ECU
bool electromotor_start
bool aux_fuel_pump # reserved
bool main_fuel_pump

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','ignition_1','ignition_2','servo','magnetic_valve','ECU','electromotor_start','aux_fuel_pump','main_fuel_pump']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ignition_1,ignition_2,servo,magnetic_valve,ECU,electromotor_start,aux_fuel_pump,main_fuel_pump

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EngineStateExt, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ignition_1 is None:
        self.ignition_1 = False
      if self.ignition_2 is None:
        self.ignition_2 = False
      if self.servo is None:
        self.servo = False
      if self.magnetic_valve is None:
        self.magnetic_valve = False
      if self.ECU is None:
        self.ECU = False
      if self.electromotor_start is None:
        self.electromotor_start = False
      if self.aux_fuel_pump is None:
        self.aux_fuel_pump = False
      if self.main_fuel_pump is None:
        self.main_fuel_pump = False
    else:
      self.header = std_msgs.msg.Header()
      self.ignition_1 = False
      self.ignition_2 = False
      self.servo = False
      self.magnetic_valve = False
      self.ECU = False
      self.electromotor_start = False
      self.aux_fuel_pump = False
      self.main_fuel_pump = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8B.pack(_x.ignition_1, _x.ignition_2, _x.servo, _x.magnetic_valve, _x.ECU, _x.electromotor_start, _x.aux_fuel_pump, _x.main_fuel_pump))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.ignition_1, _x.ignition_2, _x.servo, _x.magnetic_valve, _x.ECU, _x.electromotor_start, _x.aux_fuel_pump, _x.main_fuel_pump,) = _struct_8B.unpack(str[start:end])
      self.ignition_1 = bool(self.ignition_1)
      self.ignition_2 = bool(self.ignition_2)
      self.servo = bool(self.servo)
      self.magnetic_valve = bool(self.magnetic_valve)
      self.ECU = bool(self.ECU)
      self.electromotor_start = bool(self.electromotor_start)
      self.aux_fuel_pump = bool(self.aux_fuel_pump)
      self.main_fuel_pump = bool(self.main_fuel_pump)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8B.pack(_x.ignition_1, _x.ignition_2, _x.servo, _x.magnetic_valve, _x.ECU, _x.electromotor_start, _x.aux_fuel_pump, _x.main_fuel_pump))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.ignition_1, _x.ignition_2, _x.servo, _x.magnetic_valve, _x.ECU, _x.electromotor_start, _x.aux_fuel_pump, _x.main_fuel_pump,) = _struct_8B.unpack(str[start:end])
      self.ignition_1 = bool(self.ignition_1)
      self.ignition_2 = bool(self.ignition_2)
      self.servo = bool(self.servo)
      self.magnetic_valve = bool(self.magnetic_valve)
      self.ECU = bool(self.ECU)
      self.electromotor_start = bool(self.electromotor_start)
      self.aux_fuel_pump = bool(self.aux_fuel_pump)
      self.main_fuel_pump = bool(self.main_fuel_pump)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8B = struct.Struct("<8B")
_struct_3I = struct.Struct("<3I")
