"""autogenerated by genpy from actuators/PowerDistributionLineFailure.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PowerDistributionLineFailure(genpy.Message):
  _md5sum = "aeb2a9fcc6d05758484af0e0d800bfbb"
  _type = "actuators/PowerDistributionLineFailure"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

uint8 bottom_signal_lights_failure
uint8 top_signal_lights_failure
uint8 tail_equipment_failure
uint8 left_power_equipment_failure
uint8 right_power_equipment_failure

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','bottom_signal_lights_failure','top_signal_lights_failure','tail_equipment_failure','left_power_equipment_failure','right_power_equipment_failure']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,bottom_signal_lights_failure,top_signal_lights_failure,tail_equipment_failure,left_power_equipment_failure,right_power_equipment_failure

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PowerDistributionLineFailure, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.bottom_signal_lights_failure is None:
        self.bottom_signal_lights_failure = 0
      if self.top_signal_lights_failure is None:
        self.top_signal_lights_failure = 0
      if self.tail_equipment_failure is None:
        self.tail_equipment_failure = 0
      if self.left_power_equipment_failure is None:
        self.left_power_equipment_failure = 0
      if self.right_power_equipment_failure is None:
        self.right_power_equipment_failure = 0
    else:
      self.header = std_msgs.msg.Header()
      self.bottom_signal_lights_failure = 0
      self.top_signal_lights_failure = 0
      self.tail_equipment_failure = 0
      self.left_power_equipment_failure = 0
      self.right_power_equipment_failure = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_5B.pack(_x.bottom_signal_lights_failure, _x.top_signal_lights_failure, _x.tail_equipment_failure, _x.left_power_equipment_failure, _x.right_power_equipment_failure))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.bottom_signal_lights_failure, _x.top_signal_lights_failure, _x.tail_equipment_failure, _x.left_power_equipment_failure, _x.right_power_equipment_failure,) = _struct_5B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_5B.pack(_x.bottom_signal_lights_failure, _x.top_signal_lights_failure, _x.tail_equipment_failure, _x.left_power_equipment_failure, _x.right_power_equipment_failure))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.bottom_signal_lights_failure, _x.top_signal_lights_failure, _x.tail_equipment_failure, _x.left_power_equipment_failure, _x.right_power_equipment_failure,) = _struct_5B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_5B = struct.Struct("<5B")
